class Autogenerated {
  List<Data>? data;
  String? message;
  bool? status;
  Null? pagination;

  Autogenerated({this.data, this.message, this.status, this.pagination});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    message = json['message'];
    status = json['status'];
    pagination = json['pagination'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['message'] = this.message;
    data['status'] = this.status;
    data['pagination'] = this.pagination;
    return data;
  }
}

class Data {
  int? groupId;
  String? groupName;
  String? groupType;
  String? groupImage;

  Data({this.groupId, this.groupName, this.groupType, this.groupImage});

  Data.fromJson(Map<String, dynamic> json) {
    groupId = json['group-id'];
    groupName = json['group-name'];
    groupType = json['group-type'];
    groupImage = json['group-image'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['group-id'] = this.groupId;
    data['group-name'] = this.groupName;
    data['group-type'] = this.groupType;
    data['group-image'] = this.groupImage;
    return data;
  }
}
